anguage: java

jdk:
  - openjdk8

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

install:
  - ssh-keyscan ${ip} >> ~/.ssh/known_hosts

script:
  - mvn clean package -f classrepair-dependencies/pom.xml
  - docker build -t weacsoft:latest .
  - docker login --username=${registryu} registry.cn-shenzhen.aliyuncs.com --password=${registryp}
  - docker tag weacsoft:latest registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair
  - docker push registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'scp classrepair-system/target/*.jar /home/room/classrepair-java'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker login --username=${registryu} registry.cn-shenzhen.aliyuncs.com --password=${registryp}'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker stop classrepair && docker rm classrepair'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker stop classrepair && docker rm classrepair'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker rmi registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker pull registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker run --name classrepair --restart=always -v /home/room/log:/log -p 8085:8085 -e JAVA_OPTS=-Dspring.profiles.active=product registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair'

branches:
  only:
  - master

notifications:
  email: true
