anguage: java

jdk:
  - openjdk8

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

install:
  - ssh-keyscan ${ip} >> ~/.ssh/known_hosts

script:
  - sshpass -p ${pwd} scp ${user}@${ip}:${filepath}/application-product.yml
  - mv application-product.yml classrepair-system/src/main/resources && ls classrepair-system/src/main/resources
  - mvn clean package -f classrepair-dependencies/pom.xml
  - sshpass -p ${pwd} scp classrepair-system/target/*.jar ${user}@${ip}:${filepath}
  - docker build -t weacsoft:latest .
  - docker login --username=${registryu} registry.cn-shenzhen.aliyuncs.com --password=${registryp}
  - docker tag weacsoft:latest registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair
  - docker push registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker login --username=${registryu} registry.cn-shenzhen.aliyuncs.com --password=${registryp}'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'cd /home/room/classrepair-java && docker-compose down'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker rmi registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker pull registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'cd /home/room/classrepair-java && docker-compose up -d'

branches:
  only:
  - master

notifications:
  email: true
