anguage: java

jdk:
  - openjdk8

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

install:
  - ssh-keyscan ${ip} >> ~/.ssh/known_hosts

script:
  - sshpass -p ${pwd} scp ${user}@${ip}:${filepath}/application-product.yml .
  - mv application-product.yml classrepair-system/src/main/resources && ls classrepair-system/src/main/resources
  - mvn clean package -f classrepair-dependencies/pom.xml
  - docker build -t weacsoft:latest .
  - docker login --username=${registryu} registry.ap-northeast-1.aliyuncs.com --password=${registryp}
  - docker tag weacsoft:latest  registry.ap-northeast-1.aliyuncs.com/greenhathg/classrepair
  - docker push registry.ap-northeast-1.aliyuncs.com/greenhathg/classrepair:latest
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'cd /home/room/classrepair-java && docker-compose down'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker rmi  registry.ap-northeast-1.aliyuncs.com/greenhathg/classrepair:latest'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'docker pull  registry.ap-northeast-1.aliyuncs.com/greenhathg/classrepair:latest'
  - sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}  'cd /home/room/classrepair-java && docker-compose up -d'

branches:
  only:
  - master

notifications:
  email: true
