name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 8
      uses: actions/setup-java@master
      with:
        java-version: 8
    - name: Build and test project
      run:  mvn clean package -f classrepair-dependencies/pom.xml
    - name: Cache maven
      uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    - name: Build Docker container
      run: docker build -t weacsoft:latest .
    - name: push to aliyun
      run: |
        docker login --username=${{ secrets.registryu }} registry.cn-shenzhen.aliyuncs.com --password=${{secrets.registryp}}
        docker tag weacsoft:latest registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair
        docker push registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest
    - name: push to staging server with ssh
      env:
        ip: ${{ secrets.ssh_address }}
        port: ${{ secrets.ssh_port }}
        user: ${{ secrets.ssh_user }}
        pwd: ${{ secrets.ssh_pwd }}
      run: |
        sudo apt-get update
        sudo apt-get install sshpass -y
        sshpass -p ${pwd} ssh -o StrictHostKeyChecking=no ${user}@${ip}:${port} 'docker pull registry.cn-shenzhen.aliyuncs.com/classrepair/classrepair:latest'



